# Generated by Django 5.0.6 on 2024-07-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='post',
            name='task_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='writer',
            field=models.CharField(max_length=100),
        ),
    ]
