# Generated by Django 5.0.6 on 2024-07-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_is_completed_post_priority_post_task_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='task_date',
        ),
        migrations.AddField(
            model_name='post',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='writer',
            field=models.CharField(default='', max_length=100),
        ),
    ]
