# Generated by Django 5.0.6 on 2024-07-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_post_task_date_post_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
